version: '3.9'
services:
  postgres:
    container_name: Prefence-Center-DB
    image: "postgres:alpine3.14"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "DidomiDB"
      ALLOW_IP_RANGE: 0.0.0.0/0
  app:
    container_name: Prefence-Center-App
    image: node:14.16.1
    ports:
      - "3000:3000"
    environment:
      DOCKER: "true"
    working_dir: "/home/node/app"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: bash -c "yarn install && yarn start:dev"
    links:
      - "postgres:database"